# Generated by Django 5.2.1 on 2025-06-05 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Contact Us Messages'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('published', 'Published'), ('archived', 'Archived')], default='drafted', max_length=10),
        ),
    ]
